services:
  mywebsite:
    container_name: mywebsite
    image: mywebsite
    build:
      context: ./
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:8080"
    restart: always
